apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: <your-dockerhub>/userapp-backend
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: your-rds-endpoint.rds.amazonaws.com
            - name: DB_USER
              value: admin
            - name: DB_PASS
              value: YourSecurePassword
            - name: DB_NAME
              value: userdb
